import smtplib, ssl


class EmailNotifier:

    # Constructor method
    def __init__( self ):

        self.__port     = 465
        self.__server   = "smtp.gmail.com"
        self.__sender   = "bittutor.noreply@gmail.com"
        self.__password = "lis4021-1"
        self.__context = ssl.create_default_context()
        self.__SMTPserver = smtplib.SMTP_SSL(self.__server, self.__port, context=self.__context)
        self.__SMTPserver.login( self.__sender, self.__password )

    def sendCourseCancellationDueToReportsNotification( self, destination, username, courseName, courseDescription, instructor ):

        message = ("""\
        Subject: Course cancelled

        Hi %s:
        We're sorry to inform you that the following course:
        Name: %s
        Description: %s
        Instructor: %s

        has been cancelled due to a high number of user-reports from our community.
        Hence, you won't be able to access it any more. However stay tuned into BitTutor
        for more online learning content

        You do not need to reply to this message. It is automatically generated by the BitTutor Online Educational Platfom""") \
        % ( username, courseName, courseDescription, instructor)

        self.__SMTPserver.sendmail( self.__sender, destination, message)
